POST /news
Host: localhost:8000
Content-Type: application/json
Cookie: DNB-Auth-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NTU4MjU1NjIuNzgxNTIwNiwidXNlcl9pZCI6MiwidXNlcm5hbWUiOiJNYXR0aGV3In0.d_RaCUaOOMOaRztGD1USrtjlPGv4BeG_ryfXsmUfZWE;

{
	"title": "Berita 100",
	"description": "lorem ipsum dolor sit amet mantap",
	"date": "19/09/2022"
}