CREATE TABLE IF NOT EXISTS news (
	id SERIAL PRIMARY KEY,
	date INTEGER NOT NULL,
	title VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255) DEFAULT NULL,
	filename VARCHAR(255) DEFAULT NULL,
	archived BOOLEAN DEFAULT false,
	status BOOLEAN DEFAULT true,
	author INTEGER NOT NULL
);